# Generated by Django 5.2.11 on 2026-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='injury_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stress_baseline',
        ),
        migrations.AddField(
            model_name='checkin',
            name='post_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
