# Generated by Django 5.2.11 on 2026-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_injury_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_tone',
            field=models.CharField(blank=True, default='calm', max_length=100),
        ),
    ]
