# Generated by Django 5.2.11 on 2026-04-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback'),
        ('api', '0005_performancelog'),
    ]

    operations = [
    ]
