# Generated by Django 5.2.11 on 2026-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_feedback_category_alter_feedback_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ai_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='Short Term', max_length=20),
            preserve_default=False,
        ),
    ]
