# Generated by Django 5.2.11 on 2026-04-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedback_ai_used_feedback_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='window_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
