# Generated by Django 5.2.11 on 2026-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notif_monthly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_weekly',
            field=models.BooleanField(default=True),
        ),
    ]
